services:
  # --- 1. СЕРВІС ТОВАРІВ (Backend) ---
  product_service:
    # Формат: ghcr.io/юзернейм/репозиторій/назва_сервісу:тег
    image: ghcr.io/serg333soul/pos-system/product_service:latest
    pull_policy: always 

  # --- 3. СЕРВІС КОШИКА (Backend) ---
  order_service:
    image: ghcr.io/serg333soul/pos-system/order_service:latest
    pull_policy: always

  # --- 5. ВХІДНІ ВОРОТА (Nginx) ---
  frontend:
    image: ghcr.io/serg333soul/pos-system/frontend:latest
    pull_policy: always