name: CI/CD Pipeline

on:
  # Запускаємо на main (для деплою)
  push:
    branches: [ "main" ]
  # Запускаємо на будь-якому PR в main (для перевірок)
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # --- 1. ТЕСТИ (Запускаються ЗАВЖДИ) ---
  test:
    name: Run Unit Tests   # <--- Ось це ім'я ми шукаємо в налаштуваннях
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Імітація тесту. Пізніше тут буде 'pytest'
      - name: Run Dummy Test
        run: echo "All tests passed! System is ready."

  # --- 2. ДЕПЛОЙ (Тільки для гілки MAIN і тільки якщо тести пройшли) ---
  build-and-deploy:
    needs: test                              # Чекаємо успіху тестів
    if: github.ref == 'refs/heads/main'      # <--- ВАЖЛИВО: Не деплоїмо з тестових гілок!
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push Services
      - name: Build and push Product Service
        uses: docker/build-push-action@v4
        with:
          context: ./product_service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/product_service:latest

      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./order_service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/order_service:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
      
      # VPN & SSH
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}      
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_KEY }}    
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /mnt/ssd_storage/DevProjects/pos-system
            git pull origin main
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f